server:
    port: 9527
spring:
  application:
    name: gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
#        - 权限---刘亮
        - id: system_route #system_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-system #lb:根据服务民称从注册中心获取服务请求地址。
          predicates:
            - Path=/system/**         # 断言，路径相匹配的进行路由
#            - 药店---黄佳明
        - id: pharmacy_route #system_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-pharmacy #lb:根据服务民称从注册中心获取服务请求地址。
          predicates:
            - Path=/pharmacy/**         # 断言，路径相匹配的路由就放行
#            - 门诊病人--- 陈宇俊
        - id: outpatient_route #system_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-outpatient #lb:根据服务民称从注册中心获取服务请求地址。nacos-outpatient
          predicates:
            - Path=/outpatient/**         # 断言，路径相匹配的路由就放行
#            - 住院---谢嘉欣
        - id: inpatient_route #system_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-inpatient #lb:根据服务民称从注册中心获取服务请求地址。
          predicates:
            - Path=/inpatient/**         # 断言，路径相匹配的路由就放行
#            - 检验 --- 黄英杰
        - id: hyj_route #system_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://nacos-hyj #lb:根据服务民称从注册中心获取服务请求地址。
          predicates:
            - Path=/hyj/**         # 断言，路径相匹配的路由就放行
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos连接地址

    sentinel:
      filter:
        enabled: false # 在sentinel上不显示网关，因为要限流的是网关下的微服务
      transport:
#        配置sentinel dashboard的地址
        dashboard: localhost:8080
#        默认就是8719的端口，可以不配，假如被占用就会在8719的基础上加1，直到找到未被占用的端口
        port: 8719

